### PR TITLE
Create an installation doc for Mac OSX

### PR DESCRIPTION
**Pull request by crstffr**

### CODE REVIEW

**Comment by crstffr** [comment]
Closing, have new docs coming soon.

**Comment by topisani** [comment]
you dont have to close a PR to add commits to it - it keeps updating with your master branch :wink:

**Comment by crstffr** [comment]
i wanted to move my changes to a different branch instead of continuing to work off master.

**Comment by topisani** [comment]
oh, didnt notice, yep, that was probably a good idea

**Pull request closed without merging**
